# Numpy

Numpy is used for numerical operations on the arrays
- to install Numpy you need pip insatll numpy
- to import numpy you need to use import numpy
- we use the naming convention np for easier use so we import it as 
  import numpy as np 

In [1]:
import numpy as np
#to define an 1d array
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [2]:
#to define an 1d array
n2=np.array([[10,20,30,40],[60,70,80,90]])
n2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [3]:
#to define an 1d array
type(n1)

numpy.ndarray

In [4]:
#shape of 1d array with n attributes is given as (n,)
np.shape(n1)

(4,)

In [5]:
#shape of 2d array with m rows and n columns is given as (m,n)
np.shape(n2)

(2, 4)

In [6]:
#we use np.zeros() function to give an array with all values as zero
n3=np.zeros((1,2))

In [7]:
n3

array([[0., 0.]])

In [8]:
n5=np.zeros((5,5))
n5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#we use np.full() funtioon do define an array full of same values
n6=np.full((2,2),5)

In [10]:
n6

array([[5, 5],
       [5, 5]])

In [11]:
# we use np.arange(m,n) funtion to give an array filled with values ranging from m to n-1
n7=np.arange(10,45)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

In [54]:
n7=np.arange(0,100,5)
# the above funtion is used to to give an array with step of 5 with values in multiples of 5 in range of 0-99


In [55]:
n7

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [56]:
np.shape(n7)

(20,)

In [57]:
#nparray.reshape(M,N) is used to reshape an np array with M*N attibutes into an np array with shape M x N 
n7=n7.reshape(4,5)

In [58]:
np.shape(n7)

(4, 5)

In [59]:
n7

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [60]:
n7=n7.reshape(5,4)


In [61]:
n7

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [19]:
#np.random.randint(a,b,n) is used to generate an array of length n with values in range of a,b
n8=np.random.randint(1,100,10)
n8

array([94, 37, 60, 78, 30, 93, 61, 91,  5, 61])

In [20]:
n9=np.random.randint(1,100,10)
n9

array([14, 15, 92, 49, 90, 14, 88, 60, 42,  5])

In [62]:
n9*10

array([140, 150, 920, 490, 900, 140, 880, 600, 420,  50])

In [21]:

n10=np.vstack((n8,n9))

In [22]:
n10

array([[94, 37, 60, 78, 30, 93, 61, 91,  5, 61],
       [14, 15, 92, 49, 90, 14, 88, 60, 42,  5]])

In [23]:
n11=np.hstack((n8,n9))

In [24]:
n11

array([94, 37, 60, 78, 30, 93, 61, 91,  5, 61, 14, 15, 92, 49, 90, 14, 88,
       60, 42,  5])

In [25]:
n12=np.column_stack((n8,n9))

In [26]:
n12

array([[94, 14],
       [37, 15],
       [60, 92],
       [78, 49],
       [30, 90],
       [93, 14],
       [61, 88],
       [91, 60],
       [ 5, 42],
       [61,  5]])

In [43]:
n13=np.array([5,6,7,8,9])
n14=np.array([6,8,9,1,2])

In [44]:
np.intersect1d(n13,n14)

array([6, 8, 9])

In [45]:
np.setdiff1d(n13,n14)

array([5, 7])

In [46]:
np.setdiff1d(n14,n13)

array([1, 2])

In [47]:
np.sum([n13,n14])

61

In [48]:
np.sum([n13,n14],axis=0)

array([11, 14, 16,  9, 11])

In [49]:
np.sum([n13,n14],axis=1)

array([35, 26])

In [50]:
type(n13)


numpy.ndarray

In [51]:
np.save("series_test_save1.npy",n13)

In [52]:
n14=np.load("series_test_save1.npy")

In [53]:
n14

array([5, 6, 7, 8, 9])